apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  awsMachineType: t3.large

charts:
- name: cluster-api-aws
  override:
    sshKeyName: default
    cluster:
      name: CLUSTER_NAME
      region: ap-northeast-2
      networkSpec:
        vpc:
          ################################################################################
          ## id is a vpc-id of the VPC this provider should use to create resources. 
          ## it must set to an actual value.
          ################################################################################
          id: TO_BE_FIXED # vpc-00000000000
        ################################################################################
        ## subnets is an array of subnet configurations in VPC.
        ## it must set to an actual value.
        ################################################################################
        subnets:
        - TO_BE_FIXED
        # - id: subnets-xxxxxxxxx
    kubernetesVersion: v1.18.16
    kubeadmControlPlane.controlPlaneMachineType: $(awsMachineType)
    kubeadmControlPlane.rootVolume.size: 16
    machinePool.replicas: 3
    machinePool.machineType: $(awsMachineType)
    machinePool.rootVolume.size: 16
    ################################################################################
    ## machinePool.subnets is an array of subnet configurations in VPC.
    ## cluster api controller deploy machines in multi AZ based on provided subnets.
    ## it must set to an actual value.
    ################################################################################
    machinePool.subnets:
    - TO_BE_FIXED
    # - id: subnets-xxxxxxxxxx