apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  awsMachineType: t3.large

charts:
- name: cluster-api-aws
  override:
    sshKeyName: default
    cluster.name: TO_BE_FIXED
    cluster.region: TO_BE_FIXED
    cluster.bastion.enabled: false
    kubeadmControlPlane.controlPlaneMachineType: t3.large
    kubeadmControlPlane.rootVolume.size: 16
    machinePool.replicas: 3
    machinePool.machineType: t3.2xlarge
    machinePool.rootVolume.size: 16
- name: kubernetes-addons
  override:
    cni.calico.enabled: true
    csi.aws-ebs.enabled: true
- name: ingress-nginx
  override:
