---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: keycloak
  name: keycloak
spec:
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: keycloak
    version: 8.2.2
  releaseName: keycloak
  targetNamespace: fed
  values:
    clusterDomain: TO_BE_FIXED
    keycloak:
      extraEnv: |
        - name: KEYCLOAK_LOGLEVEL
          value: WARN
        - name: WILDFLY_LOGLEVEL
          value: WARN
      service:
        type: TO_BE_FIXED
        httpPort: 80
        httpNodePort: ""
        httpsPort: 8443
        httpsNodePort: ""
        jgroupsPort: 7600
      ingress:
        enabled: false
        hosts: []
        tls: []
      password: TO_BE_FIXED
      persistence:
        deployPostgres: true
        dbVendor: postgres
        dbUser: TO_BE_FIXED
        dbPassword: TO_BE_FIXED
    postgresql:
      postgresqlUsername: keycloak
      postgresqlPassword: TO_BE_FIXED
      postgresqlDatabase: keycloak
      persistence:
        enabled: false
        storageClass: TO_BE_FIXED
        size: TO_BE_FIXED
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cloud-console
  name: cloud-console
spec:
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: cloud-console
    version: 1.0.0
  releaseName: cloud-console
  targetNamespace: fed
  values:
    config:
      grafana:
        authkey: admin:password
      initDB: true
      kibana:
        authkey: elastic:tacoword
      password: password
      username: taco
      #config.service.proxyurl.format
      service:
        proxyportlist: 32001-32008
        proxyurl:
          format: TO_BE_FIXED
      prometheus:
        ruleUrl: /apis/monitoring.coreos.com/v1/namespaces/fed/prometheusrules
      loggingfilter:
        url: /apis/logging.kubesphere.io/v1alpha2/namespaces/lma/filters/kubernetes
      filter:
        rule: "yes"
      keycloak:
        enabled: "yes"
        url: TO_BE_FIXED  
        realm: TO_BE_FIXED
        clientId: cloud-console
        hasRealmRole1: lma_system
        hasRealmRole2: lma_app
        hasRealmRole3: lma_viewer
        cacert: TO_BE_FIXED 
      lenz:
        url: TO_BE_FIXED  
      extra:
        config: |-
        
        sql: |-

    nodeSelector:
      taco-lma: enabled
    service:
      nodePort: 32000
      port: 32000
      proxy_from: 32001
      proxy_to: 32008
      targetPort: 32000
      type: ClusterIP
    ingress:
      enabled: false
    volume:
      storageClassName: TO_BE_FIXED
      accessModes: ReadWriteOnce
  wait: true