apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: tigera-operator-crds
  name: tigera-operator-crds
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: tigera-operator
    version: v3.25.0
  releaseName: tigera-operator-crds
  targetNamespace: taco-system
  values: {}
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: tigera-operator
  name: tigera-operator
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: tigera-operator
    version: v3.25.0
    origin: https://docs.tigera.io/calico/charts
  releaseName: tigera-operator
  targetNamespace: taco-system
  values:
    tigeraOperator:
      image: tks/calico-operator
      registry: harbor.taco-cat.xyz
    calicoctl:
      image: harbor.taco-cat.xyz/tks/calico-ctl
    installation:
      registry: harbor.taco-cat.xyz/
      imagePath: tks
      imagePrefix: calico-
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: local-path-provisioner
  name: local-path-provisioner
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: local-path-provisioner
    version: 0.0.22
    origin: https://openinfradev.github.io/helm-repo
  releaseName: local-path-provisioner
  targetNamespace: taco-system
  values:
    image:
      repository: harbor.taco-cat.xyz/tks/local-path-provisioner
    storageClass:
      name: taco-storage
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: ingress-nginx
  name: ingress-nginx
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: ingress-nginx
    version: 4.0.17
    origin: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  targetNamespace: taco-system
  values:
    controller:
      image:
        registry: harbor.taco-cat.xyz
        image: tks/controller
        digest: ""
      admissionWebhooks:
        patch:
          image:
            registry: harbor.taco-cat.xyz
            image: tks/kube-webhook-certgen
            digest: ""
      replicaCount: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ingress-nginx
              topologyKey: "kubernetes.io/hostname"
      service:
        externalTrafficPolicy: Local
        annotations: {}
        type: TO_BE_FIXED
      config:
        enable-underscores-in-headers: "true"
        use-proxy-protocol: "false"
        enable-real-ip: "true"
        proxy-body-size: "10m"
      hostPort:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 4Gi
  wait: true
# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   labels:
#     name: kubeseal
#   name: kubeseal
# spec:
#   helmVersion: v3
#   chart:
#     type: helmrepo
#     repository:
#     name: kubeseal
#     version: 0.1.0
#   releaseName: kubeseal
#   targetNamespace: taco-system
#   values:

#   wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: kubed
    version: v0.12.0
    origin: https://charts.appscode.com/stable
  releaseName: kubed
  targetNamespace: taco-system
  values:

  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-autoscaler
  name: cluster-autoscaler
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: cluster-autoscaler
    version: 9.29.4
    origin: https://kubernetes.github.io/autoscaler
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  values:
    image:
      tag: TO_BE_FIXED
    cloudProvider: TO_BE_FIXED
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-autoscaler-rbac
  name: cluster-autoscaler-rbac
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: cluster-autoscaler
    version: 0.2.0
    origin: https://openinfradev.github.io/helm-repo
  releaseName: cluster-autoscaler-rbac
  targetNamespace: argo
  values:
    deployMgmtRbacOnly:
      enabled: true
      targetNamespace: TO_BE_FIXED
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: metrics-server
  name: metrics-server
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: metrics-server
    version: 3.8.2
    origin: https://kubernetes-sigs.github.io/metrics-server/
  releaseName: metrics-server
  targetNamespace: kube-system
  values:
    image:
      repository: harbor.taco-cat.xyz/tks/metrics-server
      # a value 'tag' is guided in https://artifacthub.io/packages/helm/metrics-server/metrics-server but not applied on any template
      # tag: ""
      pullPolicy: IfNotPresent
    args:
      - --kubelet-insecure-tls
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: argo-rollouts
  name: argo-rollouts
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: argo-rollouts
    version: 2.22.3
    origin: https://argoproj.github.io/argo-helm
  releaseName: argo-rollouts
  targetNamespace: taco-system
  values:
    controller:
      nodeSelector:
        taco-lma: enabled
      replicas: 2
      image:
        registry: harbor.taco-cat.xyz
        repository: tks/argo-rollouts
        tag: v1.4.1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8090"
    dashboard:
      enabled: false
      nodeSelector:
        taco-lma: enabled
      replicas: 1
      image:
        registry: harbor.taco-cat.xyz
        repository: tks/kubectl-argo-rollouts
        tag: v1.4.1
  wait: true
