---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubernetes-addons
  name: kubernetes-addons
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: kubernetes-addons
    version: 0.1.0
  releaseName: kubernetes-addons
  targetNamespace: taco-system
  values:
    cni:
      calico:
        enabled: true
    storageclass:
        enabled: false
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: local-path-provisioner
  name: local-path-provisioner
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: local-path-provisioner
    version: 0.0.22
  releaseName: local-path-provisioner
  targetNamespace: taco-system
  values:
    storageClass:
      name: taco-storage
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: ingress-nginx
  name: ingress-nginx
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: ingress-nginx
    version: 4.0.17
  releaseName: ingress-nginx
  targetNamespace: taco-system
  values:
    controller:
      replicaCount: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ingress-nginx
              topologyKey: "kubernetes.io/hostname"
      service:
        externalTrafficPolicy: Local
        annotations: {}
        type: TO_BE_FIXED
      config:
        enable-underscores-in-headers: "true"
        use-proxy-protocol: "false"
        enable-real-ip: "true"
        proxy-body-size: "10m"
      hostPort:
        enabled: true
    tcp:
      "10254": 10254:healthz
  wait: true
# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   labels:
#     name: kubeseal
#   name: kubeseal
# spec:
#   helmVersion: v3
#   chart:
#     type: helmrepo
#     repository: 
#     name: kubeseal
#     version: 0.1.0
#   releaseName: kubeseal
#   targetNamespace: taco-system
#   values:

#   wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed 
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: kubed
    version: v0.12.0
  releaseName: kubed
  targetNamespace: taco-system
  values:

  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-autoscaler
  name: cluster-autoscaler
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: cluster-autoscaler
    version: 0.2.0
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  values:
    separateMgmtClusterEnabled: true
    discoveryNamespace: TO_BE_FIXED
    discoveryClusterName: TO_BE_FIXED
    mgmtKubeconfigSecretName: mgmt-kubeconfig
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-autoscaler-rbac
  name: cluster-autoscaler-rbac
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: cluster-autoscaler
    version: 0.2.0
  releaseName: cluster-autoscaler-rbac
  targetNamespace: argo
  values:
    deployMgmtRbacOnly:
      enabled: true
      targetNamespace: TO_BE_FIXED
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: metrics-server
  name: metrics-server
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: metrics-server
    version: 3.8.2
  releaseName: metrics-server
  targetNamespace: kube-system
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      # a value 'tag' is guided in https://artifacthub.io/packages/helm/metrics-server/metrics-server but not applied on any template
      # tag: ""
      pullPolicy: IfNotPresent
    args:
      - --kubelet-insecure-tls
