apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: linuxbridge-flat-vlan

global:
  networkBackend: linuxbridge
  interfaceMappings: ""

charts:
- name: neutron
  overrides:
    conf:
      neutron:
        DEFAULT:
          l3_ha: false
          service_plugins: ""
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: $(networkBackend)
            type_drivers: flat,vlan
            tenant_network_types: ""
          ml2_type_flat:
            flat_networks: "*"
          ml2_type_vlan:
            network_vlan_ranges: provider
        openvswitch_agent:
          ovs:
            bridge_mappings: ""
        linuxbridge_agent:
          linux_bridge:
            physical_interface_mappings: $(interfaceMappings)
            bridge_mappings: ""
    network:
      backend:
      - $(networkBackend)
      share_namespaces: true
    manifests:
      daemonset_lb_agent: true
      daemonset_dhcp_agent: true
      daemonset_metadata_agent: false
      daemonset_ovs_agent: false
      daemonset_sriov_agent: false
      daemonset_l3_agent: false

