apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: openvswitch-sona

global:
  clusterName: cluster.local

charts:
- name: neutron
  override:
    conf:
      neutron:
        DEFAULT:
          l3_ha: false
          service_plugins: onos_router
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: onos_ml2
            type_drivers: flat, vlan, vxlan
            tenant_network_types: vxlan
          ml2_type_flat:
            flat_networks: '*'
          ml2_type_vlan:
            network_vlan_ranges: ""
          onos:
            url_path: http://sona-onos:8181/onos/openstacknetworking
            username: onos
            password: rocks
        openvswitch_agent:
          ovs:
            bridge_mappings: ""
        linuxbridge_agent:
          linux_bridge:
            physical_interface_mappings: ""
            bridge_mappings: null
    dependencies:
      dynamic:
        targeted:
          onos:
            dhcp.pod: null
            l3.pod: null
            lb_agent.pod: null
            metadata.pod: null
    labels:
      agent:
        dhcp:
          node_selector_value: disabled
        l3:
          node_selector_value: disabled
        metadata:
          node_selector_value: disabled
      lb:
        node_selector_value: disabled
      ovs:
        node_selector_value: disabled
    manifests:
      daemonset_lb_agent: false
      daemonset_dhcp_agent: false
      daemonset_metadata_agent: false
      daemonset_ovs_agent: false
      daemonset_sriov_agent: false
      daemonset_l3_agent: false
    network:
      backend:
      - onos
      share_namespaces: false
      server:
        node_port:
          enabled: true
          port: 30096

- name: libvirt
  override:
    dependencies.dynamic.targeted.onos.libvirt.pod: null
    network.backend:
    - onos

- name: nova
  override:
    dependencies.dynamic.targeted.onos.compute.pod: null
    network.backend:
    - onos

- name: sona
  override:
    controller:
      master: TO_BE_FIXED #controller_master_ip
      slave: TO_BE_FIXED #controller_slave_ip
    hosts: []
    # Override values inside overlay1.yaml under site directory
    #- dataIp: 192.168.11.3
    #  integrationBridge: of:0000000000000001
    #  managementIp: 172.168.12.3
    #  name: jeju-stgsvc-com01
    #  nodeType: COMPUTE
    #  phyIntfs:
    #  - intf: bond1
    #    network: baremetal
    onos:
      config:
        ovsdb_port: TO_BE_FIXED
        stateful_snat: TO_BE_FIXED
    openstack:
      endpoints:
        keystone:
          endpoint: keystone.openstack.svc.$(clusterName):80/v3
        neutron:
          endpoint: neutron.openstack.svc.$(clusterName):80
      neutron:
        novaMetadataIp: nova-metadata.openstack.svc.$(clusterName)

