apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000
charts:
- name: keycloak
  override:
    init:
      image:
        repository: $(registry)/library/busybox
        tag: 1.31
    keycloak:
      image:
        repository: $(registry)/jboss/keycloak
        tag: 10.0.0
      test:
        image:
          repository: $(registry)/unguiculus/docker-python3-phantomjs-selenium
          tag: v1
    postgresql:
      image:
        registry: $(registry)
        repository: bitnami/postgresql
        tags: 11.7.0-debian-10-r98
      volumePermissions:
        image:
          registry: $(registry)
          repository: bitnami/minideb
          tag: buster
      metrics:
        image:
          registry: $(registry)
          repository: bitnami/postgres-exporter
          tag: 0.8.0-debian-10-r106
- name: cloud-console
  override:
    image.repository: $(registry)/pseudojo/cloud-console
    image.tag: v1.0.3
    image.pullPolicy: Always