---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istio-base
  name: istio-base
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: istio-base
    version: 1.13.1
  releaseName: istio-base
  targetNamespace: istio-system
  values: {}
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istio-base-crds
  name: istio-base-crds
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: istio-base
    version: 1.13.1
  releaseName: istio-base-crds
  targetNamespace: istio-system
  values: {}
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istiod
  name: istiod
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: istiod
    version: 1.13.1
  releaseName: istiod
  targetNamespace: istio-system
  values:
    pilot:
      image: istio/pilot:1.13.1
      traceSampling: 1.0
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
      nodeSelector:
        servicemesh: enabled
    revision: ""
    global:
      istioNamespace: istio-system
      defaultResources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      hub: docker.io/istio
      tag: 1.13.1
      proxy:
        image: proxyv2
        autoInject: enabled
        clusterDomain: "cluster.local"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        tracer: "zipkin"
      tracer:
        zipkin: 
          address: "jaeger-operator-jaeger-collector.istio-system:9411"
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istio-ingress-gateway
  name: istio-ingress-gateway
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: istio-ingress-gateway
    version: 1.13.1
  releaseName: istio-ingress-gateway
  targetNamespace: istio-ingress
  values:
    image: istio/proxyv2:1.13.1
    revision: ""
    replicaCount: 1
    service:
      type: LoadBalancer
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    labels:
      app: istio-ingress-gateway
    nodeSelector:
      taco-ingress-gateway: enabled
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istio-egress-gateway
  name: istio-egress-gateway
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: istio-ingress-gateway
    version: 1.13.1
  releaseName: istio-egress-gateway
  targetNamespace: istio-ingress
  values:
    image: istio/proxyv2:1.13.1
    revision: ""
    replicaCount: 1
    service:
      type: ClusterIP
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    labels:
      app: istio-egress-gateway
    nodeSelector:
      taco-egress-gateway: enabled
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: jaeger-operator-crds
  name: jaeger-operator-crds
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: jaeger-operator
    version: 2.27.1
  releaseName: jaeger-operator-crds
  targetNamespace: istio-system
  values: {}
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    version: 2.27.1
    name: jaeger-operator
  releaseName: jaeger-operator
  targetNamespace: istio-system
  values:
    image:
      repository: jaegertracing/jaeger-operator
      tag: 1.29.1
    jaeger:
      create: false
      namespace: istio-system
    nodeSelector:
      servicemesh: enabled
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: servicemesh-jaeger-resource
  name: servicemesh-jaeger-resource
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: servicemesh-jaeger-resource
    version: 2.27.2
  releaseName: servicemesh-jaeger-resource
  targetNamespace: istio-system
  values:
    namespace: istio-system
    strategy: production
    sampling:
      param: 100
    ingress:
      enabled: false
    collector:
      image: jaegertracing/jaeger-collector:1.29.0
      maxReplicas: 5
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: servicemesh
                operator: In
                values:
                - enabled
    storage:
      esIndexCleaner:
        enabled: true
        image: jaegertracing/jaeger-es-index-cleaner:1.29.0
        numberOfDays: 7
        schedule: "55 04 * * *"
      options:
        es:
          indexPrefix: jaeger
          username: elastic
          password: tacoword
          tlsCa: /etc/ssl/certs/tls.crt
          serverUrls: https://eck-elasticsearch-es-http.elastic-system.svc:9200
          secretName: eck-elasticsearch-es-http-certs-public
    query:
      image: jaegertracing/jaeger-query:1.29.0
      basePath: /
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: servicemesh
                operator: In
                values:
                - enabled
    agent:
      image: jaegertracing/jaeger-agent:1.29.0
    elasticsearch:
      image:
        repository: docker.io/nginxinc/nginx-unprivileged
        tag: 1.19-alpine
        pullPolicy: IfNotPresent
      host: eck-elasticsearch-es-http.lma.svc.cluster.local
      port: 9200
      elasticPasswordSecret: eck-elasticsearch-es-elastic-user
      user:
        enabled: true
        username: taco-jaeger
        password: tacoword
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kiali-operator-crds
  name: kiali-operator-crds
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: kiali-operator
    version: 1.45.1
  releaseName: kiali-operator-crds
  targetNamespace: istio-system
  values: {}
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kiali-operator
  name: kiali-operator
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: kiali-operator
    version: 1.45.1
  releaseName: kiali-operator
  targetNamespace: istio-system
  values:
    image:
      repo: quay.io/kiali/kiali-operator
      tag: v1.45.1
    allowAdHocKialiImage: true
    nodeSelector:
      servicemesh: enabled
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    cr:
      create: false
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: servicemesh-kiali-resource
  name: servicemesh-kiali-resource
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: servicemesh-kiali-resource
    version: 1.45.1
  releaseName: servicemesh-kiali-resource
  targetNamespace: istio-system
  values:
    namespace: istio-system
    istioNamespace: istio-system
    deployment:
      ingress:
        enabled: false
      namespace: istio-system
      image_name: quay.io/kiali/kiali
      image_version: v1.45.1
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
      nodeSelector:
        servicemesh: enabled
      serviceType: ClusterIP
      additionalServiceYaml:
        nodePort: 30010
    auth:
      strategy: anonymous
    externalServices:
      customDashboards:
        enabled: true
      istio:
        configMapName: "istio"
        istioIdentityDomain: "svc.cluster.local"
        componentStatus:
          enabled: true
          components:
            istiodLabel: istiod
            ingressGatewayLabel: istio-ingress-gateway
            egressGatewayLabel: istio-egress-gateway
      prometheus:
        url: http://lma-prometheus.lma.svc:9090
      tracing:
        enabled: true
        namespaceSelector: true
        inClusterUrl: http://jaeger-operator-jaeger-query.istio-system:16686
        url: https://jaeger-v2.taco-cat.xyz
        useGrpc: false
      grafana:
        auth:
          password: password
          type: basic
          useKialiToken: false
          username: admin
        enabled: true
        inClusterUrl: http://grafana.lma.svc:3000
        url: https://grafana-v2.taco-cat.xyz
    server:
      metricsEnabled: true
      metricsPort: 9090
      port: 20001
      webRoot: /kiali
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: servicemesh-grafana-dashboard
  name: servicemesh-grafana-dashboard
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: servicemesh-grafana-dashboard
    version: 1.13.1
  releaseName: servicemesh-grafana-dashboard
  targetNamespace: istio-system
  values:
    namespace: istio-system
    dashboards:
      label: grafana_dashboard
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: servicemesh-prometheusmonitor
  name: servicemesh-prometheusmonitor
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: servicemesh-prometheusmonitor
    version: 1.7.0
  releaseName: servicemesh-prometheusmonitor
  targetNamespace: istio-system
  values:
    namespace: istio-system
    istio:
      interval: "15s"
    jaeger:
      interval: "15s"
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: servicemesh-prometheusrule
  name: servicemesh-prometheusrule
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: servicemesh-prometheusrule
    version: 1.7.0
  releaseName: servicemesh-prometheusrule
  targetNamespace: istio-system
  values:
    namespace: istio-system
    aggregation:
      interval: "5s"
    optimization:
      interval: "5s"
  wait: true
