---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-api-byoh
  name: cluster-api-byoh
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: cluster-api-byoh
    version: 0.3.0
  releaseName: cluster-api-byoh
  targetNamespace: argo
  values:
    cluster:
      name: TO_BE_FIXED
      kubernetesVersion: v1.22.3
    byoCluster:
      controlPlaneEndpoint:
        host: TO_BE_FIXED
        port: TO_BE_FIXED
    kubeadmControlPlane:
      replicas: 3
    machineDeployment: []
  wait: true
