apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000
charts:
- name: keycloak
  override:
    init:
      image:
        repository: $(registry)/library/busybox
        tag: 1.31
    keycloak:
      image:
        repository: $(registry)/jboss/keycloak
        tag: 10.0.0
      test:
        image:
          repository: $(registry)/unguiculus/docker-python3-phantomjs-selenium
          tag: v1
    postgresql:
      image:
        registry: $(registry)
        repository: bitnami/postgresql
        tags: 11.7.0-debian-10-r98
      volumePermissions:
        image:
          registry: $(registry)
          repository: bitnami/minideb
          tag: buster
      metrics:
        image:
          registry: $(registry)
          repository: bitnami/postgres-exporter
          tag: 0.8.0-debian-10-r106
- name: cloud-console
  override:
    image.repository: $(registry)/pseudojo/cloud-console
    image.tag: v1.0.3
    image.pullPolicy: Always
- name: custom-network
  override:
- name: taco-registry
  override:
    tacoRegistry.deployment.image: $(registry)/registry:2
    tacoDb.deployment.image:  $(registry)/postgres:latest
    tacoClair.deployment.image:  $(registry)/coreos/clair:latest
    tacoRegistryBuilder.deployment.image:  $(registry)/boozer83/taco-registry-builder:v1
    tacoRegistryApp.deployment.image: $(registry)/boozer83/taco-registry-app:v1
- name: site-mirror-registry
  override:
    tacoRegistry.deployment.image: $(registry)/registry:2

- name: keycloak-operator
  override:
    image.repository: $(registry)/keycloak/keycloak-operator
    image.tag: "17.0.0"

- name: keycloak-resources
  override:
