---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: sealed-secrets-controller
  name: sealed-secrets-controller
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 1.16.1
  releaseName: sealed-secrets-controller
  targetNamespace: kube-system
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://charts.appscode.com/stable/
    name: kubed
    version: v0.12.0-rc.3
  releaseName: kubed
  targetNamespace: kube-system
  wait: true
