---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: sealed-secrets-operator-crds
  name: sealed-secrets-operator-crds
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: sealed-secrets
    version: 1.16.1
    origin: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets-operator-crds
  targetNamespace: kube-system
  wait: true
  values: {}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: sealed-secrets-operator
  name: sealed-secrets-operator
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: sealed-secrets
    version: 1.16.1
    origin: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets-operator
  targetNamespace: kube-system
  wait: true
  values: {}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: kubed
    version: v0.12.0-rc.3
    origin: https://charts.appscode.com/stable/
  releaseName: kubed
  targetNamespace: kube-system
  wait: true
  values: {}
