---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: sealed-secrets-operator
  name: sealed-secrets-operator
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: sealed-secrets
    version: 1.16.1
    origin: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets-operator
  targetNamespace: kube-system
  wait: true
  values:
    image:
      repository: harbor.taco-cat.xyz/tks/sealed-secrets-controller
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kubed
  name: kubed
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor.taco-cat.xyz/chartrepo/tks
    name: kubed
    version: v0.12.0
    origin: https://charts.appscode.com/stable/
  releaseName: kubed
  targetNamespace: kube-system
  wait: true
  values:
    operator:
      registry: harbor.taco-cat.xyz
      repository: tks/kubed
