---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cluster-api-aws
  name: cluster-api-aws
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: cluster-api-aws
    version: 0.8.1
  releaseName: cluster-api-aws
  targetNamespace: argo
  values:
    sshKeyName: TO_BE_FIXED
    cluster:
      name: TO_BE_FIXED
      region: TO_BE_FIXED
      kubernetesVersion: v1.22.5
      podCidrBlocks:
      - 10.10.0.0/16
      bastion:
        enabled: true
        instanceType: t3.micro
        allowedCIDRBlocks:
        - 127.0.0.1/32
        useSpotInstance:
          enabled: true
    kubeadmControlPlane:
      replicas: 3
      controlPlaneMachineType: TO_BE_FIXED
      rootVolume:
        size: 20 # GB
        type: gp2
    machinePool: []
    machineDeployment: []
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: aws-ebs-csi-driver
  name: aws-ebs-csi-driver
spec:
  helmVersion: v3
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: aws-ebs-csi-driver
    version: 2.6.4-skt
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  values:
    snapshotterSidecarEnabled: true
    storageClasses: 
    - name: taco-storage
      # annotation metadata
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      # label metadata
      labels:
        support: taco-apps
      # defaults to WaitForFirstConsumer
      volumeBindingMode: WaitForFirstConsumer
      # defaults to Delete
      reclaimPolicy: Delete
      parameters:
        encrypted: "true"

  wait: true
