---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: keycloak-operator
  name: keycloak-operator
spec:
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: keycloak-operator
    version: 0.1.0
  releaseName: keycloak-operator
  targetNamespace: keycloak
  values:
    replicaCount: 1
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: keycloak-operator-crds
  name: keycloak-operator-crds
spec:
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: keycloak-operator
    version: 0.1.0
  releaseName: keycloak-operator-crds
  targetNamespace: keycloak
  values: {}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: keycloak-resources
  name: keycloak-resources
spec:
  chart:
    type: helmrepo
    repository: https://harbor-cicd.taco-cat.xyz/chartrepo/tks
    name: keycloak-resources
    version: 0.1.0
  releaseName: keycloak-resources
  targetNamespace: keycloak
  values:
    keycloak:
      name: tks-keycloak
      replicas: 1
      externalDatabase:
        enabled: true
        address: postgresql.decapod-db.svc.cluster.local # Shoud be FQDN
        port: 5432
        databaseName: keycloak
        username: keycloak
        password: keycloak
        superuserEnabled: true
      externalAccessEnabled: false
